routes:
  - host: admin.amd.thaidevops.co
    path: /
    path_type: prefix
    upstream: http://localhost:8380

  - host: api.amd.thaidevops.co
    path: /
    path_type: prefix
    upstream: http://localhost:8802
tls:
  - hosts: [admin.amd.thaidevops.co, api.amd.thaidevops.co]
    source:
      type: file
      cert: /Users/nat/projects/pertisk-tech/pertisk-proxy/certs/amd-thaidevops.pem
      key: /Users/nat/projects/pertisk-tech/pertisk-proxy/certs/amd-thaidevops.key
