{{- if and .Values.auth.enabled .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pertisk-ingress.authSecretName" . }}
  labels:
    {{- include "pertisk-ingress.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.usernameKey }}: {{ .Values.auth.username | quote }}
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | quote }}
  {{ .Values.auth.signingSecretKey }}: {{ default .Values.auth.password .Values.auth.signingSecret | quote }}
  {{- if .Values.auth.apiToken }}
  {{ .Values.auth.apiTokenKey }}: {{ .Values.auth.apiToken | quote }}
  {{- end }}
  {{- if .Values.auth0.domain }}
  {{ .Values.auth0.domainKey }}: {{ .Values.auth0.domain | quote }}
  {{ .Values.auth0.clientIdKey }}: {{ .Values.auth0.clientId | quote }}
  {{ .Values.auth0.audienceKey }}: {{ .Values.auth0.audience | quote }}
  {{- end }}
{{- end }}
