apiVersion: v1
kind: Service
metadata:
  name: {{ include "pertisk-ingress.fullname" . }}
  labels:
    {{- include "pertisk-ingress.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.externalTrafficPolicy (ne (toString .Values.service.externalTrafficPolicy) "") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (kindIs "slice" .Values.service.loadBalancerSourceRanges) (gt (len .Values.service.loadBalancerSourceRanges) 0) }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if and .Values.service.ipFamilyPolicy (ne (toString .Values.service.ipFamilyPolicy) "") }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if and (kindIs "slice" .Values.service.ipFamilies) (gt (len .Values.service.ipFamilies) 0) }}
  ipFamilies:
    {{- toYaml .Values.service.ipFamilies | nindent 4 }}
  {{- end }}
  {{- if and .Values.service.sessionAffinity (ne (toString .Values.service.sessionAffinity) "") }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.service.http3Port }}
    - name: http3
      port: {{ .Values.service.http3Port }}
      targetPort: http3
      protocol: UDP
    {{- end }}
  selector:
    {{- include "pertisk-ingress.selectorLabels" . | nindent 4 }}
